### ISSUE TITLE
Dificuldade com a instalação

### ISSUE THREAD

**Issue by volneivolff** [rafaelbozzetti/portaria.live#2]
Gostaria muito de conseguir instalar esse sistema para estudar, mas estou com dificuldade para fazer as migrations. É possível criar a estrutura do banco de dados de outra forma (para Mysql)?

**Comment by rafaelbozzetti** [comment]
Volnei, crie um .env na raiz do projeto e informe os dados a baixo. Certifique-se, também,  de ter o database criado
DB_DATABASE=portarialive
DB_USERNAME=seu_usuario
DB_PASSWORD=sua_senha
Se quiser colar o erro que ocorre, posso te ajudar.

**Comment by volneivolff** [comment]
Obrigado!

O erro era para migrar com o Phinx.  Consegui resolver modificando todas as migrations em um novo projeto Laravel. 

Ah, e parabéns pelo projeto, é demais!

**Comment by rafaelbozzetti** [comment]
ok
